

build:
	./gradlew build

install:
	./gradlew installDist

run-dist:
	./build/install/app/bin/app

help:
	./build/install/app/bin/app -h

version:
	./build/install/app/bin/app -V

lint:
	./gradlew checkstyleMain
	./gradlew checkstyleTest



PHONY: build help version
