name: Java CI

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: 'build checkstyleMain checkstyleTest'
          gradle-version: 8.7
          build-root-directory: app

