name: Java CI

on:
  - push
  - branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: 'clean build'
          gradle-version: '8.7'
          build-root-directory: './app'
      - name: Run linter
        run: ./gradlew checkstyleMain
      - run: ./gradlew test